name: Generate Contribution Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install matplotlib

      - name: Run contribution analysis script
        run: |
          python generate_report.py

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contribution-reports
          path: reports/
