name: Generate Contribution Report

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Run contribution report script
        run: python generate_report.py

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: contribution-reports
          path: reports/
